version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: recruitkart_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recruitkart
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    container_name: recruitkart_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: recruitkart_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./docker/minio_data:/data

  minio-create-bucket:
    image: minio/mc
    container_name: recruitkart_minio_create_bucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/recruitkart-media;
      /usr/bin/mc anonymous set public myminio/recruitkart-media;
      exit 0;
      "
